/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package redes_restaurante;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.util.ArrayList;
import javax.naming.spi.DirStateFactory.Result;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author KATHERINE
 */
public class Principal extends javax.swing.JFrame {
   
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        bt_cliente.setEnabled(false);
        //bt_cliente.setVisible(false);
                
        cierre.setEnabled(false);
        //cierre.setVisible(false);
        cargarTablacomida();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frame_servidor = new javax.swing.JDialog();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        JFInfo = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        apertura = new javax.swing.JButton();
        cierre = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        table_actual = new javax.swing.JTable();
        Background = new javax.swing.JLabel();
        bt_pdf = new javax.swing.JButton();
        INVENTARIO = new javax.swing.JTabbedPane();
        JFComidas = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        table_comida = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jt_precio_comida = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_descripción_comida = new javax.swing.JTextArea();
        bt_eliminar_comida = new javax.swing.JButton();
        bt_modificar_comida = new javax.swing.JButton();
        bt_agregar_comida = new javax.swing.JButton();
        js_cantidad_comida = new javax.swing.JSpinner();
        jLabel16 = new javax.swing.JLabel();
        jt_nombre_comida = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        JFBebidas = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        table_bebida = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jt_nombre_bebida = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jt_descripción_bebida = new javax.swing.JTextArea();
        bt_eliminar_bebida = new javax.swing.JButton();
        bt_modificar_bebida = new javax.swing.JButton();
        bt_agregar_bebida = new javax.swing.JButton();
        js_cantidad_bebida = new javax.swing.JSpinner();
        jt_precio_bebida = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();
        POSTRES = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        table_postre = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jt_nombre_postre = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        jt_descripción_postre = new javax.swing.JTextArea();
        bt_eliminar_postre = new javax.swing.JButton();
        bt_modificar_postre = new javax.swing.JButton();
        bt_agregar_postre = new javax.swing.JButton();
        js_cantidad_postre = new javax.swing.JSpinner();
        jt_precio_postre = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();
        MESAS = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        bgmesas = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        logout = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        login_servidor = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        bgLogin = new javax.swing.JLabel();
        MesasDialog = new javax.swing.JDialog();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        Cantidad = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        bt_cliente = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();

        frame_servidor.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JFInfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel14.setText("SMOKE");
        JFInfo.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, -1, 59));

        apertura.setBackground(new java.awt.Color(102, 102, 102));
        apertura.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        apertura.setText("Apertura");
        apertura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aperturaMouseClicked(evt);
            }
        });
        JFInfo.add(apertura, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 149, 208, 102));

        cierre.setBackground(new java.awt.Color(102, 102, 102));
        cierre.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        cierre.setText("Cierre");
        cierre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cierreMouseClicked(evt);
            }
        });
        JFInfo.add(cierre, new org.netbeans.lib.awtextra.AbsoluteConstraints(608, 149, 208, 102));

        jLabel15.setFont(new java.awt.Font("Calibri", 2, 36)); // NOI18N
        jLabel15.setText("VENTAS EN TIEMPO REAL");
        JFInfo.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 390, -1));

        table_actual.setBackground(new java.awt.Color(0, 0, 0));
        table_actual.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 13, true)));
        table_actual.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        table_actual.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cantidad", "Comida", "hora"
            }
        ));
        jScrollPane7.setViewportView(table_actual);

        JFInfo.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 605, 139));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/backgroundPageCliente.jpg"))); // NOI18N
        JFInfo.add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 650));

        bt_pdf.setText("Generar Reporte PDF");
        JFInfo.add(bt_pdf, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 535, -1, -1));

        jTabbedPane2.addTab("Info", JFInfo);

        JFComidas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table_comida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cantidad", "Nombre", "Precio", "Descripción"
            }
        ));
        table_comida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_comidaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(table_comida);

        JFComidas.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 943, 195));

        jLabel5.setFont(new java.awt.Font("Bahnschrift", 3, 18)); // NOI18N
        jLabel5.setText("Cantidad");
        JFComidas.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        jLabel6.setFont(new java.awt.Font("Bahnschrift", 3, 18)); // NOI18N
        jLabel6.setText("Nombre");
        JFComidas.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        jLabel7.setFont(new java.awt.Font("Bahnschrift", 3, 18)); // NOI18N
        jLabel7.setText("Descripción");
        JFComidas.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, -1, -1));
        JFComidas.add(jt_precio_comida, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 200, 30));

        jt_descripción_comida.setColumns(20);
        jt_descripción_comida.setRows(5);
        jScrollPane1.setViewportView(jt_descripción_comida);

        JFComidas.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, 320, 150));

        bt_eliminar_comida.setBackground(new java.awt.Color(255, 51, 51));
        bt_eliminar_comida.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        bt_eliminar_comida.setText("ELIMINAR");
        bt_eliminar_comida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_eliminar_comidaActionPerformed(evt);
            }
        });
        JFComidas.add(bt_eliminar_comida, new org.netbeans.lib.awtextra.AbsoluteConstraints(706, 446, 189, 63));

        bt_modificar_comida.setBackground(new java.awt.Color(0, 51, 153));
        bt_modificar_comida.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        bt_modificar_comida.setText("MODIFICAR");
        bt_modificar_comida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_modificar_comidaMouseClicked(evt);
            }
        });
        JFComidas.add(bt_modificar_comida, new org.netbeans.lib.awtextra.AbsoluteConstraints(706, 365, 189, 63));

        bt_agregar_comida.setBackground(new java.awt.Color(0, 153, 51));
        bt_agregar_comida.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        bt_agregar_comida.setText("AGREGAR");
        bt_agregar_comida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_agregar_comidaMouseClicked(evt);
            }
        });
        JFComidas.add(bt_agregar_comida, new org.netbeans.lib.awtextra.AbsoluteConstraints(706, 284, 189, 63));
        JFComidas.add(js_cantidad_comida, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 200, 20));

        jLabel16.setFont(new java.awt.Font("Bahnschrift", 3, 18)); // NOI18N
        jLabel16.setText("Precio");
        JFComidas.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, -1, -1));
        JFComidas.add(jt_nombre_comida, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 200, 30));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/backgroundPageCliente.jpg"))); // NOI18N
        jLabel20.setText("jLabel20");
        JFComidas.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 620));

        INVENTARIO.addTab("COMIDAS", JFComidas);

        JFBebidas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table_bebida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cantidad", "Nombre", "Precio", "Descripción"
            }
        ));
        table_bebida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_bebidaMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(table_bebida);

        JFBebidas.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 930, 190));

        jLabel8.setFont(new java.awt.Font("Bahnschrift", 3, 18)); // NOI18N
        jLabel8.setText("Cantidad");
        JFBebidas.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 257, -1, -1));

        jLabel9.setFont(new java.awt.Font("Bahnschrift", 3, 18)); // NOI18N
        jLabel9.setText("Nombre");
        JFBebidas.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 352, -1, -1));

        jLabel10.setFont(new java.awt.Font("Bahnschrift", 3, 18)); // NOI18N
        jLabel10.setText("Descripción");
        JFBebidas.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 448, -1, -1));
        JFBebidas.add(jt_nombre_bebida, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 190, 30));

        jt_descripción_bebida.setColumns(20);
        jt_descripción_bebida.setRows(5);
        jScrollPane2.setViewportView(jt_descripción_bebida);

        JFBebidas.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 450, 300, 137));

        bt_eliminar_bebida.setBackground(new java.awt.Color(255, 51, 51));
        bt_eliminar_bebida.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        bt_eliminar_bebida.setText("ELIMINAR");
        bt_eliminar_bebida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_eliminar_bebidaActionPerformed(evt);
            }
        });
        JFBebidas.add(bt_eliminar_bebida, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 410, 189, 63));

        bt_modificar_bebida.setBackground(new java.awt.Color(0, 51, 204));
        bt_modificar_bebida.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt_modificar_bebida.setText("MODIFICAR");
        bt_modificar_bebida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_modificar_bebidaMouseClicked(evt);
            }
        });
        JFBebidas.add(bt_modificar_bebida, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 330, 189, 63));

        bt_agregar_bebida.setBackground(new java.awt.Color(0, 153, 51));
        bt_agregar_bebida.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        bt_agregar_bebida.setText("AGREGAR");
        bt_agregar_bebida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_agregar_bebidaMouseClicked(evt);
            }
        });
        JFBebidas.add(bt_agregar_bebida, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 250, 189, 63));
        JFBebidas.add(js_cantidad_bebida, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 180, 30));
        JFBebidas.add(jt_precio_bebida, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 190, 30));

        jLabel17.setFont(new java.awt.Font("Bahnschrift", 3, 18)); // NOI18N
        jLabel17.setText("Precio");
        JFBebidas.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 401, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/backgroundPageCliente.jpg"))); // NOI18N
        JFBebidas.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 620));

        INVENTARIO.addTab("BEBIDAS", JFBebidas);

        POSTRES.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table_postre.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cantidad", "Nombre", "Precio", "Descripción"
            }
        ));
        table_postre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_postreMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(table_postre);

        POSTRES.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 933, 195));

        jLabel11.setFont(new java.awt.Font("Bahnschrift", 3, 18)); // NOI18N
        jLabel11.setText("Cantidad");
        POSTRES.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 285, -1, -1));

        jLabel12.setFont(new java.awt.Font("Bahnschrift", 3, 18)); // NOI18N
        jLabel12.setText("Nombre");
        POSTRES.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 365, -1, -1));

        jLabel13.setFont(new java.awt.Font("Bahnschrift", 3, 18)); // NOI18N
        jLabel13.setText("Descripción");
        POSTRES.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 465, -1, -1));
        POSTRES.add(jt_nombre_postre, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 352, 220, 30));

        jt_descripción_postre.setColumns(20);
        jt_descripción_postre.setRows(5);
        jScrollPane6.setViewportView(jt_descripción_postre);

        POSTRES.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 459, 306, 137));

        bt_eliminar_postre.setBackground(new java.awt.Color(255, 51, 51));
        bt_eliminar_postre.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        bt_eliminar_postre.setText("ELIMINAR");
        bt_eliminar_postre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_eliminar_postreActionPerformed(evt);
            }
        });
        POSTRES.add(bt_eliminar_postre, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 430, 189, 63));

        bt_modificar_postre.setBackground(new java.awt.Color(0, 51, 204));
        bt_modificar_postre.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        bt_modificar_postre.setText("MODIFICAR");
        bt_modificar_postre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_modificar_postreMouseClicked(evt);
            }
        });
        POSTRES.add(bt_modificar_postre, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 350, 189, 63));

        bt_agregar_postre.setBackground(new java.awt.Color(0, 153, 51));
        bt_agregar_postre.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        bt_agregar_postre.setText("AGREGAR");
        bt_agregar_postre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_agregar_postreMouseClicked(evt);
            }
        });
        POSTRES.add(bt_agregar_postre, new org.netbeans.lib.awtextra.AbsoluteConstraints(685, 261, 189, 63));
        POSTRES.add(js_cantidad_postre, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 282, 220, 30));

        jt_precio_postre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_precio_postreActionPerformed(evt);
            }
        });
        POSTRES.add(jt_precio_postre, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 401, 220, 30));

        jLabel18.setFont(new java.awt.Font("Bahnschrift", 3, 18)); // NOI18N
        jLabel18.setText("Precio");
        POSTRES.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 414, -1, -1));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/backgroundPageCliente.jpg"))); // NOI18N
        bg.setText("jLabel21");
        POSTRES.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 630));

        INVENTARIO.addTab("POSTRES", POSTRES);

        jTabbedPane2.addTab("Inventario", INVENTARIO);

        MESAS.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/chair.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        MESAS.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 540, -1, -1));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/chair.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        MESAS.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 380, -1, -1));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/chair.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        MESAS.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 540, -1, -1));

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/chair.png"))); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        MESAS.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 540, -1, -1));

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/meeting (1).png"))); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        MESAS.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 130, -1, -1));

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/chair.png"))); // NOI18N
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        MESAS.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 80, -1, -1));

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/chair.png"))); // NOI18N
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        MESAS.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 250, -1, -1));

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/meeting (1).png"))); // NOI18N
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        MESAS.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 390, -1, -1));

        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/meeting (1).png"))); // NOI18N
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        MESAS.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 410, -1, -1));

        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/meeting (1).png"))); // NOI18N
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        MESAS.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 270, -1, -1));

        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/order-food.png"))); // NOI18N
        MESAS.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, -1, -1));

        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/meeting (1).png"))); // NOI18N
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        MESAS.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, -1, -1));

        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/order-food.png"))); // NOI18N
        MESAS.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, -1, -1));

        jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/order-food.png"))); // NOI18N
        MESAS.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        jButton19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/order-food.png"))); // NOI18N
        MESAS.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, -1, -1));

        jButton20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/order-food.png"))); // NOI18N
        MESAS.add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        jButton21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/order-food.png"))); // NOI18N
        MESAS.add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        bgmesas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/bgMesas.jpg"))); // NOI18N
        bgmesas.setText("jLabel23");
        MESAS.add(bgmesas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1015, 642));

        jTabbedPane2.addTab("Mesas", MESAS);

        frame_servidor.getContentPane().add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 72, 1020, 670));

        jLabel4.setFont(new java.awt.Font("Bahnschrift", 3, 18)); // NOI18N
        jLabel4.setText("SERVIDOR PIZZA HUT ");
        frame_servidor.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, 220, -1));

        logout.setBackground(new java.awt.Color(255, 102, 102));
        logout.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        logout.setText("Cerrar sesión");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        frame_servidor.getContentPane().add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 20, 140, 40));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/backgroundPageCliente.jpg"))); // NOI18N
        frame_servidor.getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 840));

        jLabel2.setText("jLabel2");

        login_servidor.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("USUARIO:");
        login_servidor.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 220, 110, 40));

        jLabel19.setBackground(new java.awt.Color(204, 204, 204));
        jLabel19.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(204, 204, 204));
        jLabel19.setText("CONTRASEÑA:");
        login_servidor.getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 290, 150, 40));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        login_servidor.getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 160, 30));
        login_servidor.getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, 160, 30));

        jButton2.setBackground(new java.awt.Color(102, 102, 102));
        jButton2.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jButton2.setText("INGRESAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        login_servidor.getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 380, 110, 50));

        bgLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/backgroundLogin.jpg"))); // NOI18N
        login_servidor.getContentPane().add(bgLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 610));

        MesasDialog.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel23.setText("GESTION DE MESA");
        MesasDialog.getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, -1, -1));

        Cantidad.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Producto ", "Cantidad", "Precio"
            }
        ));
        jScrollPane8.setViewportView(Cantidad);

        MesasDialog.getContentPane().add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 508, 211));

        jButton3.setBackground(new java.awt.Color(51, 204, 0));
        jButton3.setText("GENERAR COBRO");
        MesasDialog.getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 323, 160, 40));

        jButton6.setText("AGREGARA ORDEN");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        MesasDialog.getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 130, 40));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/wallpaper food peachy.jpg"))); // NOI18N
        jLabel24.setText("jLabel24");
        MesasDialog.getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 410));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Servidor");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, -1, -1));

        bt_cliente.setText("BIENVENIDO ");
        bt_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_clienteActionPerformed(evt);
            }
        });
        getContentPane().add(bt_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 310, 70));

        jLabel1.setFont(new java.awt.Font("Calibri Light", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("RESTAURANTE PIZZA HUT");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/backgroundLogin.jpg"))); // NOI18N
        jLabel22.setText("jLabel22");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        login_servidor.setModal(true);
        login_servidor.pack();
        login_servidor.setLocationRelativeTo(this);
        login_servidor.setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    
    private void bt_agregar_comidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_agregar_comidaMouseClicked
        if(((Integer)js_cantidad_comida.getValue()<=0) || jt_nombre_comida.getText().equals("")|| jt_precio_comida.getText().equals("") || jt_descripción_comida.getText().equals("")){
            JOptionPane.showMessageDialog(frame_servidor, "Por favor, introducir todos los datos");
        }else{
            //validad si ya esta agregado en la base de datos
            try {
                
               /* String data[]={Integer.toString((Integer)js_cantidad_comida.getValue()),jt_nombre_comida.getText(),jt_precio_comida.getText(),jt_descripción_comida.getText()};
                DefaultTableModel tblModel=(DefaultTableModel)table_comida.getModel();
                tblModel.addRow(data);*/
                
                int cantidad=(Integer)js_cantidad_comida.getValue();
                String nombre=jt_nombre_comida.getText();
                String descripcion=jt_descripción_comida.getText();
                float precio=Float.parseFloat(jt_precio_comida.getText());
                
                //BASE DE DATOS
                try {
                    Connection con=Conexion.getConnection();
                    System.out.println("pasoooo");
                    PreparedStatement ps=con.prepareStatement("INSERT INTO Inventario (Nombre,Descripcion,Precio,Cantidad,Categoria) "
                            + "VALUES (?,?,?,?,?) ");
                    ps.setString(1, nombre);
                    ps.setString(2, descripcion);
                    ps.setFloat(3, precio);
                    ps.setInt(4, cantidad);
                    ps.setString(5, "comida");
                    
                    
                    ps.executeUpdate();
                    cargarTablacomida();
                    JOptionPane.showMessageDialog(frame_servidor, "Comida agregada exitosamente");
                    
                    
                } catch (Exception e) {
                    System.out.println(e.toString());
                }
                
                //Comida c=new Comida(cantidad,nombre,descripcion,precio);
                //comidas.add(c);
                
                
            } catch (Exception e) {
                
            }
            js_cantidad_comida.setValue(0);
            jt_precio_comida.setText("");
            jt_nombre_comida.setText("");
            jt_descripción_comida.setText("");
            
        }
    }//GEN-LAST:event_bt_agregar_comidaMouseClicked

    private void bt_eliminar_comidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_eliminar_comidaActionPerformed
      /* DefaultTableModel tblModel=(DefaultTableModel)table_comida.getModel();
       if(table_comida.getSelectedRowCount()==1){
           String nombretemp=tblModel.getValueAt(table_comida.getSelectedRow(), 1).toString();
           
           tblModel.removeRow(table_comida.getSelectedRow());
           
           for (int i = 0; i < comidas.size(); i++) {
               if(comidas.get(i).getNombre().equals(nombretemp)){
                   comidas.remove(i);
                   break;
               }
           }
           
           
           JOptionPane.showMessageDialog(frame_servidor, "Comida eliminada exitosamente");
       }else{
           if(table_comida.getRowCount()==0){
               //empty
               JOptionPane.showMessageDialog(frame_servidor, "La tabla esta vacia");
           }else{
               //no empty pero no esta seleccionado
               JOptionPane.showMessageDialog(frame_servidor, "Seleccione alguna fila para eliminar");
           }
       }*/
      String nombr2e=jt_nombre_comida.getText();
          
            //validad si ya esta agregado en la base de datos
            try {
                
                
                
                //BASE DE DATOS
                try {
                    Connection con=Conexion.getConnection();
                    PreparedStatement ps=con.prepareStatement("DELETE Inventario WHERE Nombre=?");
                    ps.setString(1, nombr2e);
                    ps.executeUpdate();
                    
                    cargarTablacomida();
                    JOptionPane.showMessageDialog(frame_servidor, "Comida modificada exitosamente");
                    
                    
                } catch (Exception e) {
                    System.out.println(e.toString());
                }
                
                //Comida c=new Comida(cantidad,nombre,descripcion,precio);
                //comidas.add(c);
                
                
            } catch (Exception e) {
                
            }
            js_cantidad_comida.setValue(0);
            jt_precio_comida.setText("");
            jt_nombre_comida.setText("");
            jt_descripción_comida.setText("");
            
        
    }//GEN-LAST:event_bt_eliminar_comidaActionPerformed

    private void bt_modificar_comidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_modificar_comidaMouseClicked
/*        DefaultTableModel tblModel=(DefaultTableModel)table_comida.getModel();
        
        if(table_comida.getSelectedRowCount()==1){
            String nombretemp=tblModel.getValueAt(table_comida.getSelectedRow(), 1).toString();
            
            String cantidad=Integer.toString((Integer)js_cantidad_comida.getValue());
            String nombre=jt_nombre_comida.getText();
            String precio=jt_precio_comida.getText();
            String descripcion=jt_descripción_comida.getText();
            
            tblModel.setValueAt(cantidad,table_comida.getSelectedRow(),0);
            tblModel.setValueAt(nombre,table_comida.getSelectedRow(),1);
            tblModel.setValueAt(precio,table_comida.getSelectedRow(),2);
            tblModel.setValueAt(descripcion,table_comida.getSelectedRow(),3);
            
            try {
                for (int i = 0; i < comidas.size(); i++) {
                    if(comidas.get(i).getNombre().equals(nombretemp)){
                        comidas.get(i).setCantidad((Integer)js_cantidad_comida.getValue());
                        comidas.get(i).setNombre(jt_nombre_comida.getText());
                        comidas.get(i).setPrecio(Float.parseFloat(jt_precio_comida.getText()));
                        comidas.get(i).setDescripción(jt_descripción_comida.getText());
                    }
                }
            } catch (Exception e) {
            }
            
            
            JOptionPane.showMessageDialog(frame_servidor, "Comida actualizada exitosamente");
            js_cantidad_comida.setValue(0);
            jt_precio_comida.setText("");
            jt_nombre_comida.setText("");
            jt_descripción_comida.setText("");
        }else{
            if(table_comida.getRowCount()==0){
                JOptionPane.showMessageDialog(frame_servidor, "La tabla esta vacia");
            }else{
                JOptionPane.showMessageDialog(frame_servidor, "Seleccione alguna fila para actualizar");
            }
        }*/
          //String nombre2=jt_nombre_comida.getText();
          if(((Integer)js_cantidad_comida.getValue()<=0) || jt_nombre_comida.getText().equals("")|| jt_precio_comida.getText().equals("") || jt_descripción_comida.getText().equals("")){
            JOptionPane.showMessageDialog(frame_servidor, "Por favor, introducir todos los datos");
        }else{
            //validad si ya esta agregado en la base de datos
            try {
                
               /* String data[]={Integer.toString((Integer)js_cantidad_comida.getValue()),jt_nombre_comida.getText(),jt_precio_comida.getText(),jt_descripción_comida.getText()};
                DefaultTableModel tblModel=(DefaultTableModel)table_comida.getModel();
                tblModel.addRow(data);*/
                
                int cantidad=(Integer)js_cantidad_comida.getValue();
                String nombre=jt_nombre_comida.getText();
                String descripcion=jt_descripción_comida.getText();
                float precio=Float.parseFloat(jt_precio_comida.getText());
                
                //BASE DE DATOS
                try {
                    Connection con=Conexion.getConnection();
                    PreparedStatement ps=con.prepareStatement("UPDATE Inventario SET Nombre=? ,Descripcion=?,Precio=?,Cantidad=? "
                            + "WHERE Nombre=? ");
                    ps.setString(1, nombre);
                    ps.setString(2, descripcion);
                    ps.setFloat(3, precio);
                    ps.setInt(4, cantidad);
                    ps.setString(5, nombresito_comida);
                    
                    
                    ps.executeUpdate();
                    cargarTablacomida();
                    JOptionPane.showMessageDialog(frame_servidor, "Comida modificada exitosamente");
                    
                    
                } catch (Exception e) {
                    System.out.println(e.toString());
                }
                
                //Comida c=new Comida(cantidad,nombre,descripcion,precio);
                //comidas.add(c);
                
                
            } catch (Exception e) {
                
            }
            js_cantidad_comida.setValue(0);
            jt_precio_comida.setText("");
            jt_nombre_comida.setText("");
            jt_descripción_comida.setText("");
            
        }
    }//GEN-LAST:event_bt_modificar_comidaMouseClicked

    private void table_comidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_comidaMouseClicked
        DefaultTableModel tblModel=(DefaultTableModel)table_comida.getModel();
        
        String cantidad="";
        String nombre="";
        String precio="";
        String descripcion="";
        try {
            int fila=table_comida.getSelectedRow();
            String idnombre=table_comida.getValueAt(fila, 1).toString();
            
            PreparedStatement ps;
            ResultSet rs;
            
            Connection con=Conexion.getConnection();
            ps=con.prepareStatement("SELECT Cantidad,Nombre,Precio,Descripcion FROM Inventario WHERE Nombre=?");
            ps.setString(1, idnombre);
            rs= ps.executeQuery();
            
            while( rs.next()){
                cantidad=rs.getString("Cantidad");
                nombre=rs.getString("Nombre");
                precio=rs.getString("Precio");
                descripcion=rs.getString("Descripcion");
                
            }
            
            cargarTablacomida();
            js_cantidad_comida.setValue(Integer.parseInt(cantidad));
            nombresito_comida=nombre;
             jt_nombre_comida.setText(nombre);
            jt_precio_comida.setText(precio);
            jt_descripción_comida.setText(descripcion);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(frame_servidor, e.toString());
        }
        
        
    }//GEN-LAST:event_table_comidaMouseClicked

    private void table_bebidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_bebidaMouseClicked
        DefaultTableModel tblModel=(DefaultTableModel)table_bebida.getModel();
        
        String cantidad="";
        String nombre="";
        String precio="";
        String descripcion="";
        try {
            int fila=table_bebida.getSelectedRow();
            String idnombre=table_bebida.getValueAt(fila, 1).toString();
            
            PreparedStatement ps;
            ResultSet rs;
            
            Connection con=Conexion.getConnection();
            ps=con.prepareStatement("SELECT Cantidad,Nombre,Precio,Descripcion FROM Inventario WHERE Nombre=?");
            ps.setString(1, idnombre);
            rs= ps.executeQuery();
            
            while( rs.next()){
                cantidad=rs.getString("Cantidad");
                nombre=rs.getString("Nombre");
                precio=rs.getString("Precio");
                descripcion=rs.getString("Descripcion");
                
            }
            
            cargarTablacomida();
            js_cantidad_bebida.setValue(Integer.parseInt(cantidad));
            nombresito_bebida=nombre;
             jt_nombre_bebida.setText(nombre);
            jt_precio_bebida.setText(precio);
            jt_descripción_bebida.setText(descripcion);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(frame_servidor, e.toString());
        }
        
        
    }//GEN-LAST:event_table_bebidaMouseClicked

    private void table_postreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_postreMouseClicked
        DefaultTableModel tblModel=(DefaultTableModel)table_postre.getModel();
        
        String cantidad="";
        String nombre="";
        String precio="";
        String descripcion="";
        try {
            int fila=table_postre.getSelectedRow();
            String idnombre=table_postre.getValueAt(fila, 1).toString();
            
            PreparedStatement ps;
            ResultSet rs;
            
            Connection con=Conexion.getConnection();
            ps=con.prepareStatement("SELECT Cantidad,Nombre,Precio,Descripcion FROM Inventario WHERE Nombre=?");
            ps.setString(1, idnombre);
            rs= ps.executeQuery();
            
            while( rs.next()){
                cantidad=rs.getString("Cantidad");
                nombre=rs.getString("Nombre");
                precio=rs.getString("Precio");
                descripcion=rs.getString("Descripcion");
                
            }
            
            cargarTablacomida();
            js_cantidad_postre.setValue(Integer.parseInt(cantidad));
            nombresito_postre=nombre;
             jt_nombre_postre.setText(nombre);
            jt_precio_postre.setText(precio);
            jt_descripción_postre.setText(descripcion);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(frame_servidor, e.toString());
        }
        
        
    }//GEN-LAST:event_table_postreMouseClicked

    private void bt_eliminar_bebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_eliminar_bebidaActionPerformed
      String nombr2e=jt_nombre_bebida.getText();
          
            //validad si ya esta agregado en la base de datos
            try {
                
                
                
                //BASE DE DATOS
                try {
                    Connection con=Conexion.getConnection();
                    PreparedStatement ps=con.prepareStatement("DELETE Inventario WHERE Nombre=?");
                    ps.setString(1, nombr2e);
                    ps.executeUpdate();
                    
                    cargarTablacomida();
                    JOptionPane.showMessageDialog(frame_servidor, "Comida modificada exitosamente");
                    
                    
                } catch (Exception e) {
                    System.out.println(e.toString());
                }
                
                //Comida c=new Comida(cantidad,nombre,descripcion,precio);
                //comidas.add(c);
                
                
            } catch (Exception e) {
                
            }
            js_cantidad_bebida.setValue(0);
            jt_precio_bebida.setText("");
            jt_nombre_bebida.setText("");
            jt_descripción_bebida.setText("");
            
        
    }//GEN-LAST:event_bt_eliminar_bebidaActionPerformed

    private void bt_modificar_bebidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_modificar_bebidaMouseClicked
          if(((Integer)js_cantidad_bebida.getValue()<=0) || jt_nombre_bebida.getText().equals("")|| jt_precio_bebida.getText().equals("") || jt_descripción_bebida.getText().equals("")){
            JOptionPane.showMessageDialog(frame_servidor, "Por favor, introducir todos los datos");
        }else{
            //validad si ya esta agregado en la base de datos
            try {
                
               /* String data[]={Integer.toString((Integer)js_cantidad_comida.getValue()),jt_nombre_comida.getText(),jt_precio_comida.getText(),jt_descripción_comida.getText()};
                DefaultTableModel tblModel=(DefaultTableModel)table_comida.getModel();
                tblModel.addRow(data);*/
                
                int cantidad=(Integer)js_cantidad_bebida.getValue();
                String nombre=jt_nombre_bebida.getText();
                String descripcion=jt_descripción_bebida.getText();
                float precio=Float.parseFloat(jt_precio_bebida.getText());
                
                //BASE DE DATOS
                try {
                    Connection con=Conexion.getConnection();
                    PreparedStatement ps=con.prepareStatement("UPDATE Inventario SET Nombre=? ,Descripcion=?,Precio=?,Cantidad=? "
                            + "WHERE Nombre=? ");
                    ps.setString(1, nombre);
                    ps.setString(2, descripcion);
                    ps.setFloat(3, precio);
                    ps.setInt(4, cantidad);
                    ps.setString(5, nombresito_bebida);
                    
                    
                    ps.executeUpdate();
                    cargarTablacomida();
                    JOptionPane.showMessageDialog(frame_servidor, "Comida modificada exitosamente");
                    
                    
                } catch (Exception e) {
                    System.out.println(e.toString());
                }
                
                //Comida c=new Comida(cantidad,nombre,descripcion,precio);
                //comidas.add(c);
                
                
            } catch (Exception e) {
                
            }
            js_cantidad_bebida.setValue(0);
            jt_precio_bebida.setText("");
            jt_nombre_bebida.setText("");
            jt_descripción_bebida.setText("");
            
        }
    }//GEN-LAST:event_bt_modificar_bebidaMouseClicked

    private void bt_agregar_bebidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_agregar_bebidaMouseClicked
        if(((Integer)js_cantidad_bebida.getValue()<=0) || jt_nombre_bebida.getText().equals("")|| jt_precio_bebida.getText().equals("") || jt_descripción_bebida.getText().equals("")){
            JOptionPane.showMessageDialog(frame_servidor, "Por favor, introducir todos los datos");
        }else{
            //validad si ya esta agregado en la base de datos
            try {
                
               /* String data[]={Integer.toString((Integer)js_cantidad_comida.getValue()),jt_nombre_comida.getText(),jt_precio_comida.getText(),jt_descripción_comida.getText()};
                DefaultTableModel tblModel=(DefaultTableModel)table_comida.getModel();
                tblModel.addRow(data);*/
                
                int cantidad=(Integer)js_cantidad_bebida.getValue();
                String nombre=jt_nombre_bebida.getText();
                String descripcion=jt_descripción_bebida.getText();
                float precio=Float.parseFloat(jt_precio_bebida.getText());
                
                //BASE DE DATOS
                try {
                    Connection con=Conexion.getConnection();
                    System.out.println("pasoooo");
                    PreparedStatement ps=con.prepareStatement("INSERT INTO Inventario (Nombre,Descripcion,Precio,Cantidad,Categoria) "
                            + "VALUES (?,?,?,?,?) ");
                    ps.setString(1, nombre);
                    ps.setString(2, descripcion);
                    ps.setFloat(3, precio);
                    ps.setInt(4, cantidad);
                    ps.setString(5, "comida");
                    
                    
                    ps.executeUpdate();
                    cargarTablacomida();
                    JOptionPane.showMessageDialog(frame_servidor, "Comida agregada exitosamente");
                    
                    
                } catch (Exception e) {
                    System.out.println(e.toString());
                }
                
                //Comida c=new Comida(cantidad,nombre,descripcion,precio);
                //comidas.add(c);
                
                
            } catch (Exception e) {
                
            }
            js_cantidad_comida.setValue(0);
            jt_precio_comida.setText("");
            jt_nombre_comida.setText("");
            jt_descripción_comida.setText("");
            
        }
    }//GEN-LAST:event_bt_agregar_bebidaMouseClicked

    private void bt_eliminar_postreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_eliminar_postreActionPerformed
      String nombr2e=jt_nombre_postre.getText();
          
            //validad si ya esta agregado en la base de datos
            try {
                
                
                
                //BASE DE DATOS
                try {
                    Connection con=Conexion.getConnection();
                    PreparedStatement ps=con.prepareStatement("DELETE Inventario WHERE Nombre=?");
                    ps.setString(1, nombr2e);
                    ps.executeUpdate();
                    
                    cargarTablacomida();
                    JOptionPane.showMessageDialog(frame_servidor, "Comida modificada exitosamente");
                    
                    
                } catch (Exception e) {
                    System.out.println(e.toString());
                }
                
                //Comida c=new Comida(cantidad,nombre,descripcion,precio);
                //comidas.add(c);
                
                
            } catch (Exception e) {
                
            }
            js_cantidad_postre.setValue(0);
            jt_precio_postre.setText("");
            jt_nombre_postre.setText("");
            jt_descripción_postre.setText("");
            
        
    }//GEN-LAST:event_bt_eliminar_postreActionPerformed

    private void bt_modificar_postreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_modificar_postreMouseClicked
          if(((Integer)js_cantidad_postre.getValue()<=0) || jt_nombre_postre.getText().equals("")|| jt_precio_postre.getText().equals("") || jt_descripción_postre.getText().equals("")){
            JOptionPane.showMessageDialog(frame_servidor, "Por favor, introducir todos los datos");
        }else{
            //validad si ya esta agregado en la base de datos
            try {
                
               /* String data[]={Integer.toString((Integer)js_cantidad_comida.getValue()),jt_nombre_comida.getText(),jt_precio_comida.getText(),jt_descripción_comida.getText()};
                DefaultTableModel tblModel=(DefaultTableModel)table_comida.getModel();
                tblModel.addRow(data);*/
                
                int cantidad=(Integer)js_cantidad_postre.getValue();
                String nombre=jt_nombre_postre.getText();
                String descripcion=jt_descripción_postre.getText();
                float precio=Float.parseFloat(jt_precio_postre.getText());
                
                //BASE DE DATOS
                try {
                    Connection con=Conexion.getConnection();
                    PreparedStatement ps=con.prepareStatement("UPDATE Inventario SET Nombre=? ,Descripcion=?,Precio=?,Cantidad=? "
                            + "WHERE Nombre=? ");
                    ps.setString(1, nombre);
                    ps.setString(2, descripcion);
                    ps.setFloat(3, precio);
                    ps.setInt(4, cantidad);
                    ps.setString(5, nombresito_postre);
                    
                    
                    ps.executeUpdate();
                    cargarTablacomida();
                    JOptionPane.showMessageDialog(frame_servidor, "Comida modificada exitosamente");
                    
                    
                } catch (Exception e) {
                    System.out.println(e.toString());
                }
                
                //Comida c=new Comida(cantidad,nombre,descripcion,precio);
                //comidas.add(c);
                
                
            } catch (Exception e) {
                
            }
            js_cantidad_postre.setValue(0);
            jt_precio_postre.setText("");
            jt_nombre_postre.setText("");
            jt_descripción_postre.setText("");
            
        }
    }//GEN-LAST:event_bt_modificar_postreMouseClicked

    private void bt_agregar_postreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_agregar_postreMouseClicked
        if(((Integer)js_cantidad_postre.getValue()<=0) || jt_nombre_postre.getText().equals("")|| jt_precio_postre.getText().equals("") || jt_descripción_postre.getText().equals("")){
            JOptionPane.showMessageDialog(frame_servidor, "Por favor, introducir todos los datos");
        }else{
            //validad si ya esta agregado en la base de datos
            try {
                
               /* String data[]={Integer.toString((Integer)js_cantidad_comida.getValue()),jt_nombre_comida.getText(),jt_precio_comida.getText(),jt_descripción_comida.getText()};
                DefaultTableModel tblModel=(DefaultTableModel)table_comida.getModel();
                tblModel.addRow(data);*/
                
                int cantidad=(Integer)js_cantidad_postre.getValue();
                String nombre=jt_nombre_postre.getText();
                String descripcion=jt_descripción_postre.getText();
                float precio=Float.parseFloat(jt_precio_postre.getText());
                
                //BASE DE DATOS
                try {
                    Connection con=Conexion.getConnection();
                    System.out.println("pasoooo");
                    PreparedStatement ps=con.prepareStatement("INSERT INTO Inventario (Nombre,Descripcion,Precio,Cantidad,Categoria) "
                            + "VALUES (?,?,?,?,?) ");
                    ps.setString(1, nombre);
                    ps.setString(2, descripcion);
                    ps.setFloat(3, precio);
                    ps.setInt(4, cantidad);
                    ps.setString(5, "comida");
                    
                    
                    ps.executeUpdate();
                    cargarTablacomida();
                    JOptionPane.showMessageDialog(frame_servidor, "Comida agregada exitosamente");
                    
                    
                } catch (Exception e) {
                    System.out.println(e.toString());
                }
                
                //Comida c=new Comida(cantidad,nombre,descripcion,precio);
                //comidas.add(c);
                
                
            } catch (Exception e) {
                
            }
            js_cantidad_postre.setValue(0);
            jt_precio_postre.setText("");
            jt_nombre_postre.setText("");
            jt_descripción_postre.setText("");
            
        }    }//GEN-LAST:event_bt_agregar_postreMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked

        frame_servidor.setVisible(false);
    }//GEN-LAST:event_logoutMouseClicked

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutActionPerformed

    private void aperturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aperturaMouseClicked
        JOptionPane.showMessageDialog(frame_servidor, "¡Restaurante aperturado!\nYa pueden entrar los clientes");
        bt_cliente.setEnabled(true);
        //bt_cliente.setVisible(true);
        
        cierre.setEnabled(true);
        //cierre.setVisible(true);
        
        apertura.setEnabled(false);
        //apertura.setVisible(false);
    }//GEN-LAST:event_aperturaMouseClicked

    private void cierreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cierreMouseClicked
     JOptionPane.showMessageDialog(frame_servidor, "¡Restaurante cerrado!\nCaja cerrada");
        bt_cliente.setEnabled(false);
       // bt_cliente.setVisible(false);
        
        apertura.setEnabled(true);
       // apertura.setVisible(true);
        
        cierre.setEnabled(false);
        //cierre.setVisible(false);
        
        //Generar reporte del dia
        
        
    }//GEN-LAST:event_cierreMouseClicked

    private void jt_precio_postreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_precio_postreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_precio_postreActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        login_servidor.setVisible(false);//Oculpar modal si este logra logearse
        frame_servidor.setVisible(true);//Mostrar las opciones al usuario
        frame_servidor.pack();//Ajustar modal 
            // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
MesasDialog.setVisible(true);
MesasDialog.pack();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void bt_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_clienteActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
MesasDialog.setVisible(true);
MesasDialog.pack();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
MesasDialog.setVisible(true);
MesasDialog.pack();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
MesasDialog.setVisible(true);
MesasDialog.pack();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
MesasDialog.setVisible(true);
MesasDialog.pack();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
MesasDialog.setVisible(true);
MesasDialog.pack();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
MesasDialog.setVisible(true);
MesasDialog.pack();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
MesasDialog.setVisible(true);
MesasDialog.pack();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
MesasDialog.setVisible(true);
MesasDialog.pack();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
MesasDialog.setVisible(true);
MesasDialog.pack();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
MesasDialog.setVisible(true);
MesasDialog.pack();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JTable Cantidad;
    private javax.swing.JTabbedPane INVENTARIO;
    private javax.swing.JPanel JFBebidas;
    private javax.swing.JPanel JFComidas;
    private javax.swing.JPanel JFInfo;
    private javax.swing.JPanel MESAS;
    private javax.swing.JDialog MesasDialog;
    private javax.swing.JPanel POSTRES;
    private javax.swing.JButton apertura;
    private javax.swing.JLabel background;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel bgLogin;
    private javax.swing.JLabel bgmesas;
    private javax.swing.JButton bt_agregar_bebida;
    private javax.swing.JButton bt_agregar_comida;
    private javax.swing.JButton bt_agregar_postre;
    private javax.swing.JButton bt_cliente;
    private javax.swing.JButton bt_eliminar_bebida;
    private javax.swing.JButton bt_eliminar_comida;
    private javax.swing.JButton bt_eliminar_postre;
    private javax.swing.JButton bt_modificar_bebida;
    private javax.swing.JButton bt_modificar_comida;
    private javax.swing.JButton bt_modificar_postre;
    private javax.swing.JButton bt_pdf;
    private javax.swing.JButton cierre;
    private javax.swing.JDialog frame_servidor;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JSpinner js_cantidad_bebida;
    private javax.swing.JSpinner js_cantidad_comida;
    private javax.swing.JSpinner js_cantidad_postre;
    private javax.swing.JTextArea jt_descripción_bebida;
    private javax.swing.JTextArea jt_descripción_comida;
    private javax.swing.JTextArea jt_descripción_postre;
    private javax.swing.JTextField jt_nombre_bebida;
    private javax.swing.JTextField jt_nombre_comida;
    private javax.swing.JTextField jt_nombre_postre;
    private javax.swing.JTextField jt_precio_bebida;
    private javax.swing.JTextField jt_precio_comida;
    private javax.swing.JTextField jt_precio_postre;
    private javax.swing.JDialog login_servidor;
    private javax.swing.JButton logout;
    private javax.swing.JTable table_actual;
    private javax.swing.JTable table_bebida;
    private javax.swing.JTable table_comida;
    private javax.swing.JTable table_postre;
    // End of variables declaration//GEN-END:variables
    ArrayList<Comida> comidas=new ArrayList();
    ArrayList<Bebida> bebidas=new ArrayList();
    ArrayList<Postre> postres=new ArrayList();
    
    int cont_numplato=1;
    
    String nombresito_comida="",nombresito_bebida="",nombresito_postre="";
    
    
    
    private void cargarTablacomida(){
        DefaultTableModel modeloTabla=(DefaultTableModel)table_comida.getModel();
        modeloTabla.setRowCount(0);
        
        PreparedStatement ps;
        ResultSet rs;
        ResultSetMetaData rsmd;
        int columnas;
        
        int[] anchos={100,100,100,100};
        for (int i = 0; i < table_comida.getColumnCount(); i++) {
            table_comida.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
            
        }
        
        
        try {
             Connection con=Conexion.getConnection();
             ps=con.prepareStatement("SELECT Cantidad,Nombre,Precio,Descripcion FROM Inventario");
             
             rs=ps.executeQuery();
             rsmd=rs.getMetaData();
             columnas=rsmd.getColumnCount();
             
             while(rs.next()){
                 Object[] fila=new Object[columnas];
                 for (int i = 0; i < columnas; i++) {
                     fila[i]=rs.getObject(i+1);
                 }
                 modeloTabla.addRow(fila);
             }
             
             
        } catch (Exception e) {
            JOptionPane.showMessageDialog(frame_servidor, e.toString());
        }
    }
}
