/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package redes_restaurante;

import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author KATHERINE
 */
public class Principal extends javax.swing.JFrame {
   
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        bt_cliente.setEnabled(false);
        //bt_cliente.setVisible(false);
                
        cierre.setEnabled(false);
        //cierre.setVisible(false);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        login_servidor = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_usuario = new javax.swing.JTextField();
        tf_contraseña = new javax.swing.JTextField();
        bt_login_servidor = new javax.swing.JButton();
        frame_servidor = new javax.swing.JDialog();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        INFO = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        apertura = new javax.swing.JButton();
        cierre = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        table_actual = new javax.swing.JTable();
        bt_pdf = new javax.swing.JButton();
        INVENTARIO = new javax.swing.JTabbedPane();
        COMIDAS = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        table_comida = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jt_precio_comida = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_descripción_comida = new javax.swing.JTextArea();
        bt_eliminar_comida = new javax.swing.JButton();
        bt_modificar_comida = new javax.swing.JButton();
        bt_agregar_comida = new javax.swing.JButton();
        js_cantidad_comida = new javax.swing.JSpinner();
        jLabel16 = new javax.swing.JLabel();
        jt_nombre_comida = new javax.swing.JTextField();
        BEBIDAS = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        table_bebida = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jt_nombre_bebida = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jt_descripción_bebida = new javax.swing.JTextArea();
        bt_eliminar_bebida = new javax.swing.JButton();
        bt_modificar_bebida = new javax.swing.JButton();
        bt_agregar_bebida = new javax.swing.JButton();
        js_cantidad_bebida = new javax.swing.JSpinner();
        jt_precio_bebida = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        POSTRES = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        table_postre = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jt_nombre_postre = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        jt_descripción_postre = new javax.swing.JTextArea();
        bt_eliminar_postre = new javax.swing.JButton();
        bt_modificar_postre = new javax.swing.JButton();
        bt_agregar_postre = new javax.swing.JButton();
        js_cantidad_postre = new javax.swing.JSpinner();
        jt_precio_postre = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        MESAS = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        logout = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        bt_cliente = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jPanel2.setAlignmentX(0.0F);
        jPanel2.setAlignmentY(0.0F);

        jLabel2.setText("Usuario");

        jLabel3.setText("Contraseña");

        bt_login_servidor.setText("ENTRAR");
        bt_login_servidor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_login_servidorMouseClicked(evt);
            }
        });
        bt_login_servidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_login_servidorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(52, 52, 52)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(bt_login_servidor)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addComponent(bt_login_servidor)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout login_servidorLayout = new javax.swing.GroupLayout(login_servidor.getContentPane());
        login_servidor.getContentPane().setLayout(login_servidorLayout);
        login_servidorLayout.setHorizontalGroup(
            login_servidorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        login_servidorLayout.setVerticalGroup(
            login_servidorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(login_servidorLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel14.setText("SMOKE");

        apertura.setText("Apertura");
        apertura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aperturaMouseClicked(evt);
            }
        });

        cierre.setText("Cierre");
        cierre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cierreMouseClicked(evt);
            }
        });

        jLabel15.setText("Ventas en tiempo real");

        table_actual.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cantidad", "Comida", "hora"
            }
        ));
        jScrollPane7.setViewportView(table_actual);

        bt_pdf.setText("Generar Reporte PDF");

        javax.swing.GroupLayout INFOLayout = new javax.swing.GroupLayout(INFO);
        INFO.setLayout(INFOLayout);
        INFOLayout.setHorizontalGroup(
            INFOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(INFOLayout.createSequentialGroup()
                .addGroup(INFOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(INFOLayout.createSequentialGroup()
                        .addGap(423, 423, 423)
                        .addComponent(jLabel14))
                    .addGroup(INFOLayout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addGroup(INFOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_pdf)
                            .addGroup(INFOLayout.createSequentialGroup()
                                .addComponent(apertura, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 226, Short.MAX_VALUE)
                                .addComponent(cierre, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(187, 187, 187))
        );
        INFOLayout.setVerticalGroup(
            INFOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(INFOLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(INFOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apertura, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cierre, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(bt_pdf)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Info", INFO);

        table_comida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cantidad", "Nombre", "Precio", "Descripción"
            }
        ));
        table_comida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_comidaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(table_comida);

        jLabel5.setText("Cantidad");

        jLabel6.setText("Nombre");

        jLabel7.setText("Descripción");

        jt_descripción_comida.setColumns(20);
        jt_descripción_comida.setRows(5);
        jScrollPane1.setViewportView(jt_descripción_comida);

        bt_eliminar_comida.setText("ELIMINAR");
        bt_eliminar_comida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_eliminar_comidaActionPerformed(evt);
            }
        });

        bt_modificar_comida.setText("MODIFICAR");
        bt_modificar_comida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_modificar_comidaMouseClicked(evt);
            }
        });

        bt_agregar_comida.setText("AGREGAR");
        bt_agregar_comida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_agregar_comidaMouseClicked(evt);
            }
        });

        jLabel16.setText("Precio");

        javax.swing.GroupLayout COMIDASLayout = new javax.swing.GroupLayout(COMIDAS);
        COMIDAS.setLayout(COMIDASLayout);
        COMIDASLayout.setHorizontalGroup(
            COMIDASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(COMIDASLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(COMIDASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(COMIDASLayout.createSequentialGroup()
                        .addComponent(jScrollPane3)
                        .addContainerGap())
                    .addGroup(COMIDASLayout.createSequentialGroup()
                        .addGroup(COMIDASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5)
                            .addComponent(jLabel16))
                        .addGap(38, 38, 38)
                        .addGroup(COMIDASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(COMIDASLayout.createSequentialGroup()
                                .addGroup(COMIDASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jt_precio_comida, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 220, Short.MAX_VALUE)
                                .addGroup(COMIDASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bt_eliminar_comida, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bt_modificar_comida, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(COMIDASLayout.createSequentialGroup()
                                .addGroup(COMIDASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(js_cantidad_comida, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jt_nombre_comida, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bt_agregar_comida, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(105, 105, 105))))
        );
        COMIDASLayout.setVerticalGroup(
            COMIDASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(COMIDASLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(COMIDASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(COMIDASLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(COMIDASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(js_cantidad_comida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(COMIDASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jt_nombre_comida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(80, 80, 80)
                        .addGroup(COMIDASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(COMIDASLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addComponent(bt_agregar_comida, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(COMIDASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt_modificar_comida, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(jt_precio_comida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(bt_eliminar_comida, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105))))
        );

        INVENTARIO.addTab("COMIDAS", COMIDAS);

        table_bebida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cantidad", "Nombre", "Precio", "Descripción"
            }
        ));
        table_bebida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_bebidaMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(table_bebida);

        jLabel8.setText("Cantidad");

        jLabel9.setText("Nombre");

        jLabel10.setText("Descripción");

        jt_descripción_bebida.setColumns(20);
        jt_descripción_bebida.setRows(5);
        jScrollPane2.setViewportView(jt_descripción_bebida);

        bt_eliminar_bebida.setText("ELIMINAR");
        bt_eliminar_bebida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_eliminar_bebidaActionPerformed(evt);
            }
        });

        bt_modificar_bebida.setText("MODIFICAR");
        bt_modificar_bebida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_modificar_bebidaMouseClicked(evt);
            }
        });

        bt_agregar_bebida.setText("AGREGAR");
        bt_agregar_bebida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_agregar_bebidaMouseClicked(evt);
            }
        });

        jLabel17.setText("Precio");

        javax.swing.GroupLayout BEBIDASLayout = new javax.swing.GroupLayout(BEBIDAS);
        BEBIDAS.setLayout(BEBIDASLayout);
        BEBIDASLayout.setHorizontalGroup(
            BEBIDASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BEBIDASLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(BEBIDASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel17))
                .addGap(41, 41, 41)
                .addGroup(BEBIDASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(js_cantidad_bebida, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jt_nombre_bebida)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(jt_precio_bebida))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(BEBIDASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BEBIDASLayout.createSequentialGroup()
                        .addComponent(bt_modificar_bebida, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(139, 139, 139))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BEBIDASLayout.createSequentialGroup()
                        .addComponent(bt_agregar_bebida, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(137, 137, 137))
                    .addGroup(BEBIDASLayout.createSequentialGroup()
                        .addComponent(bt_eliminar_bebida, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(BEBIDASLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 930, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 53, Short.MAX_VALUE))
        );
        BEBIDASLayout.setVerticalGroup(
            BEBIDASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BEBIDASLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(BEBIDASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(js_cantidad_bebida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_agregar_bebida, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(BEBIDASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BEBIDASLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(bt_modificar_bebida, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(bt_eliminar_bebida, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(BEBIDASLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addGroup(BEBIDASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jt_nombre_bebida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(BEBIDASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jt_precio_bebida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(BEBIDASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29))))
        );

        INVENTARIO.addTab("BEBIDAS", BEBIDAS);

        table_postre.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cantidad", "Nombre", "Precio", "Descripción"
            }
        ));
        table_postre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_postreMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(table_postre);

        jLabel11.setText("Cantidad");

        jLabel12.setText("Nombre");

        jLabel13.setText("Descripción");

        jt_descripción_postre.setColumns(20);
        jt_descripción_postre.setRows(5);
        jScrollPane6.setViewportView(jt_descripción_postre);

        bt_eliminar_postre.setText("ELIMINAR");
        bt_eliminar_postre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_eliminar_postreActionPerformed(evt);
            }
        });

        bt_modificar_postre.setText("MODIFICAR");
        bt_modificar_postre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_modificar_postreMouseClicked(evt);
            }
        });

        bt_agregar_postre.setText("AGREGAR");
        bt_agregar_postre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_agregar_postreMouseClicked(evt);
            }
        });

        jt_precio_postre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_precio_postreActionPerformed(evt);
            }
        });

        jLabel18.setText("Precio");

        javax.swing.GroupLayout POSTRESLayout = new javax.swing.GroupLayout(POSTRES);
        POSTRES.setLayout(POSTRESLayout);
        POSTRESLayout.setHorizontalGroup(
            POSTRESLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(POSTRESLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(POSTRESLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, POSTRESLayout.createSequentialGroup()
                        .addGroup(POSTRESLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel18))
                        .addGap(65, 65, 65)
                        .addGroup(POSTRESLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(POSTRESLayout.createSequentialGroup()
                                .addComponent(js_cantidad_postre, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bt_agregar_postre, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(POSTRESLayout.createSequentialGroup()
                                .addGroup(POSTRESLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                                    .addComponent(jt_nombre_postre)
                                    .addComponent(jt_precio_postre, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(POSTRESLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bt_eliminar_postre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bt_modificar_postre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(126, 126, 126))
                    .addGroup(POSTRESLayout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 933, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(37, Short.MAX_VALUE))))
        );
        POSTRESLayout.setVerticalGroup(
            POSTRESLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, POSTRESLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_eliminar_postre, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
            .addGroup(POSTRESLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(POSTRESLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_agregar_postre, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(js_cantidad_postre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(POSTRESLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jt_nombre_postre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(POSTRESLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(POSTRESLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(bt_modificar_postre, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(POSTRESLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel13))
                    .addGroup(POSTRESLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(POSTRESLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jt_precio_postre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );

        INVENTARIO.addTab("POSTRES", POSTRES);

        jTabbedPane2.addTab("Inventario", INVENTARIO);

        javax.swing.GroupLayout MESASLayout = new javax.swing.GroupLayout(MESAS);
        MESAS.setLayout(MESASLayout);
        MESASLayout.setHorizontalGroup(
            MESASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1003, Short.MAX_VALUE)
        );
        MESASLayout.setVerticalGroup(
            MESASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 631, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Mesas", MESAS);

        jLabel4.setText("SERVIDOR");

        logout.setText("Cerrar sesión");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout frame_servidorLayout = new javax.swing.GroupLayout(frame_servidor.getContentPane());
        frame_servidor.getContentPane().setLayout(frame_servidorLayout);
        frame_servidorLayout.setHorizontalGroup(
            frame_servidorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frame_servidorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frame_servidorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frame_servidorLayout.createSequentialGroup()
                        .addComponent(jTabbedPane2)
                        .addContainerGap())
                    .addGroup(frame_servidorLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logout)
                        .addGap(27, 27, 27))))
        );
        frame_servidorLayout.setVerticalGroup(
            frame_servidorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frame_servidorLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(frame_servidorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(logout))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 1000));

        jButton1.setText("Servidor");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        bt_cliente.setText("BIENVENIDO ");

        jLabel1.setText("NOMBRE DEL RESTAURANTE AQUÍ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(335, 335, 335)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(bt_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(255, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jButton1)
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(137, 137, 137)
                .addComponent(bt_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(669, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        login_servidor.setModal(true);
        login_servidor.pack();
        login_servidor.setLocationRelativeTo(this);
        login_servidor.setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    private void bt_login_servidorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_login_servidorMouseClicked
        //inicio de sesión servidor
        String usuario="admin";
        String contraseña="1";
        if(tf_usuario.getText().equals(usuario) && tf_contraseña.getText().equals(contraseña)){
            login_servidor.setVisible(false);
            tf_usuario.setText("");
            tf_contraseña.setText("");
            
            frame_servidor.setModal(true);
            frame_servidor.pack();
            frame_servidor.setLocationRelativeTo(this);
            frame_servidor.setVisible(true);
            
            
        }else{
            JOptionPane.showMessageDialog(login_servidor, "ACCESO DENEGADO","ERROR",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bt_login_servidorMouseClicked

    private void bt_agregar_comidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_agregar_comidaMouseClicked
        if(((Integer)js_cantidad_comida.getValue()<=0) || jt_nombre_comida.getText().equals("")|| jt_precio_comida.getText().equals("") || jt_descripción_comida.getText().equals("")){
            JOptionPane.showMessageDialog(frame_servidor, "Por favor, introducir todos los datos");
        }else{
            //validad si ya esta agregado en la base de datos
            try {
                
                String data[]={Integer.toString((Integer)js_cantidad_comida.getValue()),jt_nombre_comida.getText(),jt_precio_comida.getText(),jt_descripción_comida.getText()};
                DefaultTableModel tblModel=(DefaultTableModel)table_comida.getModel();
                tblModel.addRow(data);
                
                int cantidad=(Integer)js_cantidad_comida.getValue();
                String nombre=jt_nombre_comida.getText();
                String descripcion=jt_descripción_comida.getText();
                float precio=Float.parseFloat(jt_precio_comida.getText());
                Comida c=new Comida(cantidad,nombre,descripcion,precio);
                comidas.add(c);
                
                JOptionPane.showMessageDialog(frame_servidor, "Comida agregada exitosamente");
            } catch (Exception e) {
                
            }
            js_cantidad_comida.setValue(0);
            jt_precio_comida.setText("");
            jt_nombre_comida.setText("");
            jt_descripción_comida.setText("");
            
        }
    }//GEN-LAST:event_bt_agregar_comidaMouseClicked

    private void bt_eliminar_comidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_eliminar_comidaActionPerformed
       DefaultTableModel tblModel=(DefaultTableModel)table_comida.getModel();
       if(table_comida.getSelectedRowCount()==1){
           String nombretemp=tblModel.getValueAt(table_comida.getSelectedRow(), 1).toString();
           
           tblModel.removeRow(table_comida.getSelectedRow());
           
           for (int i = 0; i < comidas.size(); i++) {
               if(comidas.get(i).getNombre().equals(nombretemp)){
                   comidas.remove(i);
                   break;
               }
           }
           
           
           JOptionPane.showMessageDialog(frame_servidor, "Comida eliminada exitosamente");
       }else{
           if(table_comida.getRowCount()==0){
               //empty
               JOptionPane.showMessageDialog(frame_servidor, "La tabla esta vacia");
           }else{
               //no empty pero no esta seleccionado
               JOptionPane.showMessageDialog(frame_servidor, "Seleccione alguna fila para eliminar");
           }
       }
    }//GEN-LAST:event_bt_eliminar_comidaActionPerformed

    private void bt_modificar_comidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_modificar_comidaMouseClicked
        DefaultTableModel tblModel=(DefaultTableModel)table_comida.getModel();
        
        if(table_comida.getSelectedRowCount()==1){
            String nombretemp=tblModel.getValueAt(table_comida.getSelectedRow(), 1).toString();
            
            String cantidad=Integer.toString((Integer)js_cantidad_comida.getValue());
            String nombre=jt_nombre_comida.getText();
            String precio=jt_precio_comida.getText();
            String descripcion=jt_descripción_comida.getText();
            
            tblModel.setValueAt(cantidad,table_comida.getSelectedRow(),0);
            tblModel.setValueAt(nombre,table_comida.getSelectedRow(),1);
            tblModel.setValueAt(precio,table_comida.getSelectedRow(),2);
            tblModel.setValueAt(descripcion,table_comida.getSelectedRow(),3);
            
            try {
                for (int i = 0; i < comidas.size(); i++) {
                    if(comidas.get(i).getNombre().equals(nombretemp)){
                        comidas.get(i).setCantidad((Integer)js_cantidad_comida.getValue());
                        comidas.get(i).setNombre(jt_nombre_comida.getText());
                        comidas.get(i).setPrecio(Float.parseFloat(jt_precio_comida.getText()));
                        comidas.get(i).setDescripción(jt_descripción_comida.getText());
                    }
                }
            } catch (Exception e) {
            }
            
            
            JOptionPane.showMessageDialog(frame_servidor, "Comida actualizada exitosamente");
            js_cantidad_comida.setValue(0);
            jt_precio_comida.setText("");
            jt_nombre_comida.setText("");
            jt_descripción_comida.setText("");
        }else{
            if(table_comida.getRowCount()==0){
                JOptionPane.showMessageDialog(frame_servidor, "La tabla esta vacia");
            }else{
                JOptionPane.showMessageDialog(frame_servidor, "Seleccione alguna fila para actualizar");
            }
        }
        
        
    }//GEN-LAST:event_bt_modificar_comidaMouseClicked

    private void table_comidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_comidaMouseClicked
        DefaultTableModel tblModel=(DefaultTableModel)table_comida.getModel();
        
        String cantidad=tblModel.getValueAt(table_comida.getSelectedRow(), 0).toString();
        String nombre=tblModel.getValueAt(table_comida.getSelectedRow(), 1).toString();
        String precio=tblModel.getValueAt(table_comida.getSelectedRow(), 2).toString();
        String descripcion=tblModel.getValueAt(table_comida.getSelectedRow(), 3).toString();
        
        js_cantidad_comida.setValue(Integer.parseInt(cantidad));
        jt_nombre_comida.setText(nombre);
        jt_precio_comida.setText(precio);
        jt_descripción_comida.setText(descripcion);
    }//GEN-LAST:event_table_comidaMouseClicked

    private void bt_login_servidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_login_servidorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_login_servidorActionPerformed

    private void table_bebidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_bebidaMouseClicked
        DefaultTableModel tblModel=(DefaultTableModel)table_bebida.getModel();
        
        String cantidad=tblModel.getValueAt(table_bebida.getSelectedRow(), 0).toString();
        String nombre=tblModel.getValueAt(table_bebida.getSelectedRow(), 1).toString();
        String precio=tblModel.getValueAt(table_bebida.getSelectedRow(), 2).toString();
        String descripcion=tblModel.getValueAt(table_bebida.getSelectedRow(), 3).toString();
        
        js_cantidad_bebida.setValue(Integer.parseInt(cantidad));
        jt_nombre_bebida.setText(nombre);
        jt_precio_bebida.setText(precio);
        jt_descripción_bebida.setText(descripcion);
        
    }//GEN-LAST:event_table_bebidaMouseClicked

    private void table_postreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_postreMouseClicked
        DefaultTableModel tblModel=(DefaultTableModel)table_postre.getModel();
        
        String cantidad=tblModel.getValueAt(table_postre.getSelectedRow(), 0).toString();
        String nombre=tblModel.getValueAt(table_postre.getSelectedRow(), 1).toString();
        String precio=tblModel.getValueAt(table_postre.getSelectedRow(), 2).toString();
        String descripcion=tblModel.getValueAt(table_postre.getSelectedRow(), 3).toString();
        
        js_cantidad_postre.setValue(Integer.parseInt(cantidad));
        jt_nombre_postre.setText(nombre);
        jt_precio_postre.setText(precio);
        jt_descripción_postre.setText(descripcion);
        
    }//GEN-LAST:event_table_postreMouseClicked

    private void bt_eliminar_bebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_eliminar_bebidaActionPerformed
       DefaultTableModel tblModel=(DefaultTableModel)table_bebida.getModel();
       if(table_bebida.getSelectedRowCount()==1){
           String nombretemp=tblModel.getValueAt(table_comida.getSelectedRow(), 1).toString();
           
           tblModel.removeRow(table_bebida.getSelectedRow());
           
           for (int i = 0; i < bebidas.size(); i++) {
               if(bebidas.get(i).getNombre().equals(nombretemp)){
                   bebidas.remove(i);
                   break;
               }
           }
           JOptionPane.showMessageDialog(frame_servidor, "Bebida eliminada exitosamente");
       }else{
           if(table_bebida.getRowCount()==0){
               //empty
               JOptionPane.showMessageDialog(frame_servidor, "La tabla esta vacia");
           }else{
               //no empty pero no esta seleccionado
               JOptionPane.showMessageDialog(frame_servidor, "Seleccione alguna fila para eliminar");
           }
       }
    }//GEN-LAST:event_bt_eliminar_bebidaActionPerformed

    private void bt_modificar_bebidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_modificar_bebidaMouseClicked
        DefaultTableModel tblModel=(DefaultTableModel)table_bebida.getModel();
        
        if(table_bebida.getSelectedRowCount()==1){
            String nombretemp=tblModel.getValueAt(table_comida.getSelectedRow(), 1).toString();
            
            String cantidad=Integer.toString((Integer)js_cantidad_bebida.getValue());
            String nombre=jt_nombre_bebida.getText();
            String precio=jt_precio_bebida.getText();
            String descripcion=jt_descripción_bebida.getText();
            
            tblModel.setValueAt(cantidad,table_bebida.getSelectedRow(),0);
            tblModel.setValueAt(nombre,table_bebida.getSelectedRow(),1);
            tblModel.setValueAt(precio,table_bebida.getSelectedRow(),2);
            tblModel.setValueAt(descripcion,table_bebida.getSelectedRow(),3);
            
            try {
                for (int i = 0; i < bebidas.size(); i++) {
                    if(bebidas.get(i).getNombre().equals(nombretemp)){
                        bebidas.get(i).setCantidad((Integer)js_cantidad_bebida.getValue());
                        bebidas.get(i).setNombre(jt_nombre_bebida.getText());
                        bebidas.get(i).setPrecio(Float.parseFloat(jt_precio_bebida.getText()));
                        bebidas.get(i).setDescripción(jt_descripción_bebida.getText());
                    }
                }
            } catch (Exception e) {
            }
            
            
            JOptionPane.showMessageDialog(frame_servidor, "Bebida actualizada exitosamente");
            js_cantidad_bebida.setValue(0);
            jt_nombre_bebida.setText("");
            jt_precio_bebida.setText("");
            jt_descripción_bebida.setText("");
        }else{
            if(table_bebida.getRowCount()==0){
                JOptionPane.showMessageDialog(frame_servidor, "La tabla esta vacia");
            }else{
                JOptionPane.showMessageDialog(frame_servidor, "Seleccione alguna fila para actualizar");
            }
        }
    }//GEN-LAST:event_bt_modificar_bebidaMouseClicked

    private void bt_agregar_bebidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_agregar_bebidaMouseClicked
         if(((Integer)js_cantidad_bebida.getValue()<=0) || jt_nombre_bebida.getText().equals("") ||jt_precio_bebida.getText().equals("") || jt_descripción_bebida.getText().equals("")){
            JOptionPane.showMessageDialog(frame_servidor, "Por favor, introducir todos los datos");
        }else{
            //validad si ya esta agregado
             try {
                   String data[]={Integer.toString((Integer)js_cantidad_bebida.getValue()),jt_nombre_bebida.getText(),jt_precio_bebida.getText(),jt_descripción_bebida.getText()};
                DefaultTableModel tblModel=(DefaultTableModel)table_bebida.getModel();
                tblModel.addRow(data);
                
                int cantidad=(Integer)js_cantidad_bebida.getValue();
                String nombre=jt_nombre_bebida.getText();
                String descripcion=jt_descripción_bebida.getText();
                float precio=Float.parseFloat(jt_precio_bebida.getText());
                Bebida b =new Bebida(cantidad,nombre,descripcion,precio);
                bebidas.add(b);
                
                JOptionPane.showMessageDialog(frame_servidor, "Bebida agregada exitosamente");
             } catch (Exception e) {
             }
              
            
            
            
            js_cantidad_bebida.setValue(0);
            jt_nombre_bebida.setText("");
            jt_precio_bebida.setText("");
            jt_descripción_bebida.setText("");
            
        }
    }//GEN-LAST:event_bt_agregar_bebidaMouseClicked

    private void bt_eliminar_postreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_eliminar_postreActionPerformed
        DefaultTableModel tblModel=(DefaultTableModel)table_postre.getModel();
       if(table_postre.getSelectedRowCount()==1){
           String nombretemp=tblModel.getValueAt(table_comida.getSelectedRow(), 1).toString();
    
           tblModel.removeRow(table_postre.getSelectedRow());
          
           for (int i = 0; i < postres.size(); i++) {
               if(postres.get(i).getNombre().equals(nombretemp)){
                   postres.remove(i);
                   break;
               }
           }
           
           JOptionPane.showMessageDialog(frame_servidor, "Postre eliminado exitosamente");
       }else{
           if(table_postre.getRowCount()==0){
               //empty
               JOptionPane.showMessageDialog(frame_servidor, "La tabla esta vacia");
           }else{
               //no empty pero no esta seleccionado
               JOptionPane.showMessageDialog(frame_servidor, "Seleccione alguna fila para eliminar");
           }
       }
    }//GEN-LAST:event_bt_eliminar_postreActionPerformed

    private void bt_modificar_postreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_modificar_postreMouseClicked
        DefaultTableModel tblModel=(DefaultTableModel)table_postre.getModel();
        
        if(table_postre.getSelectedRowCount()==1){
            String nombretemp=tblModel.getValueAt(table_comida.getSelectedRow(), 1).toString();
            
            String cantidad=Integer.toString((Integer)js_cantidad_postre.getValue());
            String nombre=jt_nombre_postre.getText();
            String precio=jt_precio_postre.getText();
            String descripcion=jt_descripción_postre.getText();
            
            tblModel.setValueAt(cantidad,table_postre.getSelectedRow(),0);
            tblModel.setValueAt(nombre,table_postre.getSelectedRow(),1);
            tblModel.setValueAt(precio,table_postre.getSelectedRow(),2);
            tblModel.setValueAt(descripcion,table_postre.getSelectedRow(),3);
            
            try {
                for (int i = 0; i < postres.size(); i++) {
                    if(postres.get(i).getNombre().equals(nombretemp)){
                        postres.get(i).setCantidad((Integer)js_cantidad_postre.getValue());
                        postres.get(i).setNombre(jt_nombre_postre.getText());
                        postres.get(i).setPrecio(Float.parseFloat(jt_precio_postre.getText()));
                        postres.get(i).setDescripción(jt_descripción_postre.getText());
                    }
                }
            } catch (Exception e) {
            }
            
            JOptionPane.showMessageDialog(frame_servidor, "Postre actualizado exitosamente");
            js_cantidad_postre.setValue(0);
            jt_nombre_postre.setText("");
            jt_precio_postre.setText("");
            jt_descripción_postre.setText("");
        }else{
            if(table_postre.getRowCount()==0){
                JOptionPane.showMessageDialog(frame_servidor, "La tabla esta vacia");
            }else{
                JOptionPane.showMessageDialog(frame_servidor, "Seleccione alguna fila para actualizar");
            }
        }
    }//GEN-LAST:event_bt_modificar_postreMouseClicked

    private void bt_agregar_postreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_agregar_postreMouseClicked
        if(((Integer)js_cantidad_postre.getValue()<=0) || jt_nombre_postre.getText().equals("") || jt_precio_postre.getText().equals("")|| jt_descripción_postre.getText().equals("")){
            JOptionPane.showMessageDialog(frame_servidor, "Por favor, introducir todos los datos");
        }else{
            //validad si ya esta agregado
            //VALIDAR BIEN ESTOOOOO DESPUES
            
            try {
                String data[]={Integer.toString((Integer)js_cantidad_postre.getValue()),jt_nombre_postre.getText(),jt_precio_postre.getText(),jt_descripción_postre.getText()};
                DefaultTableModel tblModel=(DefaultTableModel)table_postre.getModel();
                tblModel.addRow(data);
                
                int cantidad=(Integer)js_cantidad_postre.getValue();
                String nombre=jt_nombre_postre.getText();
                String descripcion=jt_descripción_postre.getText();
                float precio=Float.parseFloat(jt_precio_postre.getText());
                Postre p=new Postre(cantidad,nombre,descripcion,precio);
                postres.add(p);
                
                JOptionPane.showMessageDialog(frame_servidor, "Postre agregado exitosamente");
            } catch (Exception e) {
            }
                
            
            
            
            js_cantidad_postre.setValue(0);
            jt_nombre_postre.setText("");
            jt_precio_postre.setText("");
            jt_descripción_postre.setText("");
            
        }
    }//GEN-LAST:event_bt_agregar_postreMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked

        frame_servidor.setVisible(false);
    }//GEN-LAST:event_logoutMouseClicked

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutActionPerformed

    private void aperturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aperturaMouseClicked
        JOptionPane.showMessageDialog(frame_servidor, "¡Restaurante aperturado!\nYa pueden entrar los clientes");
        bt_cliente.setEnabled(true);
        //bt_cliente.setVisible(true);
        
        cierre.setEnabled(true);
        //cierre.setVisible(true);
        
        apertura.setEnabled(false);
        //apertura.setVisible(false);
    }//GEN-LAST:event_aperturaMouseClicked

    private void cierreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cierreMouseClicked
     JOptionPane.showMessageDialog(frame_servidor, "¡Restaurante cerrado!\nCaja cerrada");
        bt_cliente.setEnabled(false);
       // bt_cliente.setVisible(false);
        
        apertura.setEnabled(true);
       // apertura.setVisible(true);
        
        cierre.setEnabled(false);
        //cierre.setVisible(false);
        
        //Generar reporte del dia
        
        
    }//GEN-LAST:event_cierreMouseClicked

    private void jt_precio_postreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_precio_postreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_precio_postreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BEBIDAS;
    private javax.swing.JPanel COMIDAS;
    private javax.swing.JPanel INFO;
    private javax.swing.JTabbedPane INVENTARIO;
    private javax.swing.JPanel MESAS;
    private javax.swing.JPanel POSTRES;
    private javax.swing.JButton apertura;
    private javax.swing.JButton bt_agregar_bebida;
    private javax.swing.JButton bt_agregar_comida;
    private javax.swing.JButton bt_agregar_postre;
    private javax.swing.JButton bt_cliente;
    private javax.swing.JButton bt_eliminar_bebida;
    private javax.swing.JButton bt_eliminar_comida;
    private javax.swing.JButton bt_eliminar_postre;
    private javax.swing.JButton bt_login_servidor;
    private javax.swing.JButton bt_modificar_bebida;
    private javax.swing.JButton bt_modificar_comida;
    private javax.swing.JButton bt_modificar_postre;
    private javax.swing.JButton bt_pdf;
    private javax.swing.JButton cierre;
    private javax.swing.JDialog frame_servidor;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JSpinner js_cantidad_bebida;
    private javax.swing.JSpinner js_cantidad_comida;
    private javax.swing.JSpinner js_cantidad_postre;
    private javax.swing.JTextArea jt_descripción_bebida;
    private javax.swing.JTextArea jt_descripción_comida;
    private javax.swing.JTextArea jt_descripción_postre;
    private javax.swing.JTextField jt_nombre_bebida;
    private javax.swing.JTextField jt_nombre_comida;
    private javax.swing.JTextField jt_nombre_postre;
    private javax.swing.JTextField jt_precio_bebida;
    private javax.swing.JTextField jt_precio_comida;
    private javax.swing.JTextField jt_precio_postre;
    private javax.swing.JDialog login_servidor;
    private javax.swing.JButton logout;
    private javax.swing.JTable table_actual;
    private javax.swing.JTable table_bebida;
    private javax.swing.JTable table_comida;
    private javax.swing.JTable table_postre;
    private javax.swing.JTextField tf_contraseña;
    private javax.swing.JTextField tf_usuario;
    // End of variables declaration//GEN-END:variables
    ArrayList<Comida> comidas=new ArrayList();
    ArrayList<Bebida> bebidas=new ArrayList();
    ArrayList<Postre> postres=new ArrayList();
    
}
